frr defaults traditional
hostname frr-h1
log syslog informational
service integrated-vtysh-config
!
bfd
 profile fast
  detect-multiplier 3
  receive-interval 100
  transmit-interval 100
 exit
exit
!
interface lo
 ip address 1.1.1.1/32
exit
!
interface eth0
 ip ospf bfd
 ip ospf bfd profile fast
exit
!
router ospf
 network 1.1.1.1/32 area 0
 network 10.10.10.0/24 area 0
exit
!
